- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/execute/ProtocExecutorBuilder.java
Deterministic output/reproducible build functionality only affects the output when using --encode with protoc from a compiled descriptor, which we are not doing.
Closes GH-20.
> GH-20: Remove deterministic output functionality

- src/it/java-test-simple/src/test/java/org/example/helloworld/ProtobufTest.java
- src/it/lite-java-simple/invoker.properties
- src/it/lite-java-simple/pom.xml
- src/it/lite-java-simple/src/main/protobuf/helloworld.proto
- src/it/lite-java-simple/src/test/java/org/example/helloworld/ProtobufTest.java
- src/it/lite-java-simple/test.groovy
- src/it/lite-java-test-simple/invoker.properties
- src/it/lite-java-test-simple/pom.xml
- src/it/lite-java-test-simple/src/test/java/org/example/helloworld/ProtobufTest.java
- src/it/lite-java-test-simple/src/test/protobuf/helloworld.proto
- src/it/lite-java-test-simple/test.groovy
- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/execute/ProtocArgumentBuilder.java
- src/site/markdown/index.md
Enable generating "`lite`" sources for Java generated sources.
Closes GH-18.
> GH-18: Opt into generating lite-only sources for Java

- README.md
- src/it/java-grpc-simple/invoker.properties
- src/it/java-grpc-simple/pom.xml
- src/it/java-grpc-simple/src/main/java/org/example/helloworld/GreetingServiceImpl.java
- src/it/java-grpc-simple/src/main/protobuf/helloworld.proto
- src/it/java-grpc-simple/src/test/java/org/example/helloworld/GreetingServiceImplTest.java
- src/it/java-grpc-simple/test.groovy
- src/it/java-simple/pom.xml
- src/it/java-test-simple/pom.xml
- src/it/kotlin-test-simple/pom.xml
- src/it/lite-java-simple/pom.xml
- src/it/lite-java-test-simple/pom.xml
- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/GenerateProtobufMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/GenerateProtobufTestMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/execute/ProtocArgumentBuilder.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceGenerator.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceGeneratorBuilder.java
- src/main/java/io/github/ascopes/protobufmavenplugin/resolve/AbstractMavenCoordinateFactory.java
- src/main/java/io/github/ascopes/protobufmavenplugin/resolve/grpc/MavenGrpcJavaPluginCoordinateFactory.java
- src/main/java/io/github/ascopes/protobufmavenplugin/resolve/grpc/MavenGrpcJavaPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/resolve/grpc/MavenGrpcKotlinPluginCoordinateFactory.java
- src/main/java/io/github/ascopes/protobufmavenplugin/resolve/grpc/MavenGrpcKotlinPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/resolve/grpc/PathGrpcJavaPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/resolve/grpc/PathGrpcKotlinPluginResolver.java
- src/site/markdown/index.md
Adds ability to generate gRPC stubs for Java and optionally Kotlin by resolving the binaries from Maven central.
The plugin structure has been moved around to enable reusing components more easily.
Closes GH-24.
> GH-24: Add ability to generate gRPC stubs

- src/main/java/io/github/ascopes/protobufmavenplugin/platform/HostEnvironment.java
Always normalize and convert paths to absolute paths.
> Handle paths consistently in HostEnvironment

- src/main/java/io/github/ascopes/protobufmavenplugin/resolve/ProtoSourceResolver.java
Fix an issue that may cause confusing behaviour if the user attempts to specify a file as a source directory.
Rather than crashing or checking if that file is valid, the plugin will now emit a message and ignore the entry entirely.
> Do not attempt to walk across source directories that are not directories

- src/main/java/io/github/ascopes/protobufmavenplugin/platform/HostEnvironment.java
- Only apply distinction reduction once paths are parsed and normalized so we don't let mixed absolute and relative paths get detected as being distinct despite looking at the same file.
- Discard any trailing and leading whitespace in paths (all platforms) and path extensions (windows only).
> Handle irregular path cases better

- pom.xml
- src/it/java-import-from-jar/invoker.properties
- src/it/java-import-from-jar/pom.xml
- src/it/java-import-from-jar/src/main/protobuf/car.proto
- src/it/java-import-from-jar/test.groovy
- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/ArchiveExtractor.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/BasicMavenCoordinate.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/Executable.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/MavenArtifactResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/MavenCoordinate.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/MavenExecutableResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/ProtoSourceResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/execute/ProtocArgumentBuilder.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceGenerator.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceGeneratorBuilder.java
New features to add the ability to "import" protobuf sources from other locations, including other JARs and other directories, without including them for compilation.
This allows referencing dependencies in a similar way to how Java manages this, and provides the ability to recursively pull in these imports. This has been done because, as an example, depending on `com.google.api.grpc:proto-google-common-protos` requires protoc to be able to see the protobuf stubs in `com.google.protobuf:protobuf-java` as well.
<details>
<summary>Example configuration and output</summary>
```xml
<plugin>
<groupId>${plugin-group-id}</groupId>
<artifactId>${plugin-artifact-id}</artifactId>
<version>${plugin-version}</version>
<configuration>
<additionalImports> …
```
> GH-38: Import .proto files from maven dependencies

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
Add support for disabling the default Java outputs. This allows replacing Java generation with a different third party implementation if desired.
> Support disabling default Java code generation

- src/main/java/io/github/ascopes/protobufmavenplugin/execute/ArgLineBuilder.java
If no output targets are provided (e.g. java_out, kotlin_out, or any plugins), then fail before invoking protoc to prevent a more complicated error.
> Error if no output target paths are provided

- .github/workflows/build.yml
Use the Codecov GitHub action so that coverage also covers Mac OS and Windows builds.
> Use GitHub action to submit coverage

- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
Skip any execution if no sources are discovered, rather than erroring when protoc is called.
> Skip execution if no sources are discovered

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/Plugin.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/BinaryPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
Provides a better validation mechanism and allows rejection of configurations that would make protoc emit a JAR directly and break the build assumptions.
Also validates plugins correctly and validates protocVersion is not LATEST which will have confusing behaviour.
Fixes GH-19.
> GH-19: Disallow output directories with .jar extensions

- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/ProtocResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/system/HostSystem.java
- src/test/java/io/github/ascopes/protobufmavenplugin/system/HostSystemTest.java
Enables emitting a warning if building on Android Termux platforms as the protoc binaries on Maven Central may not work correctly on some devices such as my own.
This warning advises users on how to work around this problem.
Closes GH-65.
> Add ability to detect Termux and warn if detected

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/site/markdown/index.md
Allow overriding protoc.version via the commandline with higher precedence than <protocVersion>.
> Allow overriding protoc.version via the commandline properly

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- src/it/test-java-main-system-protoc/invoker.properties
- src/it/test-java-main-system-protoc/pom.xml
- src/it/test-java-main-system-protoc/src/main/protobuf/helloworld.proto
- src/it/test-java-main-system-protoc/src/test/java/org/example/helloworld/ProtobufTest.java
- src/it/test-java-main-system-protoc/test.groovy
Added tests for calling protoc from the system PATH.
> GH-26: Add tests for $PATH resolution of protoc

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/source/ProtoSourceResolver.java
Update exception handling to report causes correctly to Maven logs when running with `mvn -e`.
Fixes GH-86.
> GH-86: Fix exception causes being omitted from Maven output

- src/it/test-java-main-empty/invoker.properties
- src/it/test-java-main-empty/pom.xml
- src/it/test-java-test-empty/invoker.properties
- src/it/test-java-test-empty/pom.xml
- src/main/java/io/github/ascopes/protobufmavenplugin/source/ProtoSourceResolver.java
Fixes a bug where the plugin would crash if the directory for protobuf source roots did not exist. 
The plugin will now emit a message saying that no sources are found, and then exit successfully.
This prevents build failures if the plugin is accidentally inherited from a parent POM into a project that lacks any source roots.
Fixes GH-85.
> GH-85: Do not crash if source roots are missing

- .github/workflows/build.yml
- pom.xml
- src/it/invoker.properties
This enables builds to verify that the prerequisite minimum Maven version is in fact compatible with the codebase.
I have also adjusted the minimum Maven version that is supported from 3.8.0 to
3.8.1, since 3.8.0 is not available at
https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/
> Add new job to run CI against prerequisite Maven version

- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
- src/main/java/io/github/ascopes/protobufmavenplugin/source/ProtoSourceResolver.java
Uses linked structures to enforce consistent ordering of input files and discovered files during builds.
> Enforce maintaining consistent ordering between builds

- .github/workflows/validate.yml
- src/main/java/io/github/ascopes/protobufmavenplugin/platform/Shlex.java
- src/test/java/io/github/ascopes/protobufmavenplugin/platform/ShlexTest.java
- Handle \r \n and \t in shell scripts.
- Handle % in batch scripts.
Fixes GH-79.
> GH-79: Handle special characters in shell scripts better

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
Allow users to disable the registration of output directories as compiler source roots, should special edge cases come along that require this.
> Add the ability to skip registration as a compiler source root

- src/it/java-main-empty/pom.xml
- src/it/java-test-empty/pom.xml
- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
Set the default behaviour to fail the build if no sources are found to compile by protoc. This enables detecting faulty plugin configuration.
Added a new parameter to allow reverting this behaviour.
> Default to failing on missing sources.

- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/PlatformArtifactFactory.java
- src/test/java/io/github/ascopes/protobufmavenplugin/dependency/PlatformArtifactFactoryTest.java
> Fix linux detection on s390x

- .github/workflows/build.yml
- README.md
- src/it/grpc-plugin/pom.xml
- src/it/java-main-empty/pom.xml
- src/it/java-main-lite/pom.xml
- src/it/java-main-lite/src/test/java/org/example/helloworld/ProtobufLiteTest.java
- src/it/java-main/pom.xml
- src/it/java-main/src/test/java/org/example/helloworld/ProtobufTest.java
- src/it/java-test-empty/pom.xml
- src/it/java-test-lite/pom.xml
- src/it/java-test-lite/src/test/java/org/example/helloworld/ProtobufLiteTest.java
- src/it/java-test/pom.xml
- src/it/java-test/src/test/java/org/example/helloworld/ProtobufTest.java
- src/it/kotlin-main/pom.xml
- src/it/kotlin-test/pom.xml
- src/it/path-protoc/pom.xml
- src/it/reactor-grpc-binary-plugin/pom.xml
- src/it/reactor-grpc-jvm-plugin/pom.xml
- src/site/markdown/index.md
Protoc 4.26.0 has been released as a breaking change to 3.25.3 where deprecated functionality has been removed.
This fixes builds and updates all tests and examples.
Fixes GH-122.
> GH-122: Bump to protoc 4.26.0 from 3.25.3

- README.md
- pom.xml
- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/execute/ArgLineBuilder.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
This PR adds support for generating C++, Python, pyi, and Ruby sources.
By default, this is not enabled, as most users will not need this.
The functionality has been added to enable working with the GraalVM polyglot platform which allows working with C++, Python, and Ruby as common targets.
Support for PHP, C#, Objective C, and Rust has also been included to provide full coverage across the targets supported by protoc at the time of writing.
> Add support for additional languages

- .gitignore
- src/it/gh-132-duplicate-maven-dependencies/invoker.properties
- src/it/gh-132-duplicate-maven-dependencies/pom.xml
- src/it/gh-132-duplicate-maven-dependencies/some-dependency-1/pom.xml
- src/it/gh-132-duplicate-maven-dependencies/some-dependency-2/pom.xml
- src/it/gh-132-duplicate-maven-dependencies/some-dependency-3/pom.xml
- src/it/gh-132-duplicate-maven-dependencies/some-dependency-4/pom.xml
- src/it/gh-132-duplicate-maven-dependencies/some-project/invoker.properties
- src/it/gh-132-duplicate-maven-dependencies/some-project/pom.xml
- src/it/gh-132-duplicate-maven-dependencies/some-project/src/main/protobuf/helloworld.proto
- src/it/gh-132-duplicate-maven-dependencies/some-project/src/test/java/org/example/helloworld/ProtobufTest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/source/ProtoSourceResolver.java
Fixes GH-132.
Repeated dependencies are not currently de-duplicated from the classpath which leads to concurrency issues from race conditions when unpacking the same path in multiple places.
This also now deals with normalizing paths to ensure that they are handled consistently and only once even if using relative/non-normalised path patterns.
> GH-132: Fix race condition when referencing the same archived dependencies in multiple places

- pom.xml
- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/BinaryPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/JvmPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/MavenArtifact.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/MavenDependencyPathResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/PlatformArtifactFactory.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/ProtocResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/test/java/io/github/ascopes/protobufmavenplugin/dependency/PlatformArtifactFactoryTest.java
This replaces the use of DependableCoordinate and ArtifactCoordinate outside a couple of locations that depend on the artifact resolver API as implementation detail. This will allow for adjusting the internal implementation later much more easily going forwards.
The use of .setExtension on the artifact/dependency types used for parameters is now deprecated and should be replaced with .setType instead. This will be removed in v2.0.0.
While this is technically a breaking change in the code itself, the new parameter type remains fully compatible with the current parameter type, so this is not a major version bump. Users should not see any difference in the API signature when using Maven XML to configure it.
> Configure unified artifact coordinate type.

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
- src/site/markdown/index.md
The additionalImportPaths name will be retained as an alias for the parameter for backwards compatibility to prevent this being a breaking change. This will likely be removed in v2.0.0.
> Rename additionalImportPaths parameter to importPaths

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/DependencyResolutionDepth.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/DependencyResolutionScope.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/JvmPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/MavenDependencyPathResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/PlatformArtifactFactory.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
A component that makes up a small part of the overall solution for GH-135, by providing the initial ability to not include transitive dependencies implicitly, only directly specified ones.
This is achieved via a new parameter `dependencyResolutionScope` (exact name to be confirmed) which will be set to `TRANSITIVE` by default to exhibit the current resolution behaviour. It can optionally be set to `DIRECT` instead to allow only adding explicitly included dependencies to the protopath.
The change will be complimented in a future set of PRs with the ability to add dependencies without making them visible to the Java compiler, and the ability to disable reading the Java classpath dependencies at all to enable more control over how the dependency mechanism works.
> GH-135: Implement ability to only include direct dependencies

- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/JvmPluginResolver.java
Fix order of -classpath flag in JvmPluginResolver which may cause build failures on some JVMs.
> Fix order of -classpath flag in JvmPluginResolver

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/MainGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/TestGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/JvmPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/MavenDependencyPathResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
Remove the `allowedScopes` mechanism and then default to querying the already-known resolved dependencies from the Maven project itself unless direct resolution is requested.
This removes some overhead and boilerplate and simplifies the logic ready for GH-101.
> Simplify project dependency resolution

- pom.xml
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/BinaryPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/JvmPluginResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/MavenArtifact.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/MavenDependencyPathResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/MavenProjectDependencyPathResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/dependency/ProtocResolver.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
This removes the Maven Artifact Transfer dependency entirely and integrates with the Maven Dependency Resolver API directly instead. This helps make this more compatible with the future Maven 4.x API that will expect this usage and this removes a set of dependencies that we do not actually need to be using.
As a small side effect, the project dependency resolution is now even more optimised, as we no longer need to scan project dependencies again to re-resolve them when the direct resolution mode is in use. This should slightly improve build speeds in some more complicated edge cases and configurations.
Closes GH-101.
> GH-101: Use Aether artifact resolver directly

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
The version range compatibility has never worked correctly and is a suboptimal solution that does not provide reproducible builds. In v1.2.0, we are removing it entirely as it has never been supported properly.
> Remove documentation for version ranges for protoc.

- src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
Adds support for the ability to add additional import paths explicitly from archive-like artifacts on Maven repositories. This compliments the existing `importPaths` parameter and enables taking control of additional specifics of how project building works when needed in cases such as GH-135.
> GH-135: Add the ability to specify additional import dependencies explicitly

- src/main/java/io/github/ascopes/protobufmavenplugin/MainGenerateMojo.java
- src/main/java/io/github/ascopes/protobufmavenplugin/TestGenerateMojo.java
Enforce that Maven is running in online mode during builds due to the nature of how resolution is performed.
> Require Maven to be running online during execution.

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/Shlex.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ShlexTest.java
Make the command-line output visually easier to read by emitting line continuations in generated scripts and log outputs based on the platform.
> Make Shlex emit line continutations to improve command line output visually

- protobuf-maven-plugin/src/it/http-url-grpc-plugin/pom.xml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/MavenProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/PathProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/ProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/UrlProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/execute/ArgLineBuilder.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugin/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugin/JvmPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugin/ResolvedProtocPlugin.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojoTestTemplate.java
- GH-168: Add 'options' attributes to protoc plugin parameters
- Add options attribute to binaryMavenPlugins param.
- Add options attribute to jvmMavenPlugins param.
- Change binaryPathPlugins param to be a list of objects
with a name attribute (**breaking change**).
- Change binaryUrlPlugins param to be a list of objects
with a url attribute (**breaking change**).
- Add options attribute to binaryPathPlugins param.
- Add options attribute to binaryUrlPlugins param.
- Disallow setting dependencyResolutionDepth on Maven
protoc plugin params, as it should always be
ignored.
- GH-168: Propagate plugin options to protoc argline
> GH-168: Support provisionally providing options to protoc plugins

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependency/UrlResourceFetcher.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugin/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
Use optionals to handle URL resolution failures due to non-existent resources.
Prerequisite to simplifying bits of the solution in https://github.com/ascopes/protobuf-maven-plugin/issues/182 via https://github.com/ascopes/protobuf-maven-plugin/pull/189.
> Make URL resolution optional

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/MavenProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/OptionalProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/PathProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/ProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generate/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/package-info.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugin/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugin/JvmPluginResolver.java
- protobuf-maven-plugin/src/site/markdown/index.md
Implements new functionality to allow users to flag URL and path-based protoc plugins as being "optional". This enables skipping unresolvable plugins in situations where they may only be available during CI or in specific conditions.
Also implements a flag to skip plugins if desired. This allows users to control plugin execution via properties, such as by using `<skip>${protoc.grpc.skip}</skip>`.
Builds on the work contributed by @anthonyalayo in GH-183 with additional changes to improve internal APIs to robustly support the change.
Fixes GH-182.
> GH-182: Optional plugins

- protobuf-maven-plugin/src/it/grpc-plugin/test.groovy
- protobuf-maven-plugin/src/it/http-url-grpc-plugin/test.groovy
- protobuf-maven-plugin/src/it/http-url-protoc/test.groovy
- protobuf-maven-plugin/src/it/java-main-lite/test.groovy
- protobuf-maven-plugin/src/it/java-main/test.groovy
- protobuf-maven-plugin/src/it/java-paths/test.groovy
- protobuf-maven-plugin/src/it/java-test/test.groovy
- protobuf-maven-plugin/src/it/kotlin-main/test.groovy
- protobuf-maven-plugin/src/it/kotlin-test/test.groovy
- protobuf-maven-plugin/src/it/skip/invoker.properties
- protobuf-maven-plugin/src/it/skip/pom.xml
- protobuf-maven-plugin/src/it/skip/src/main/protobuf/helloworld.proto
- protobuf-maven-plugin/src/it/skip/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojoTestTemplate.java
Adds a parameter `skip` to skip plugin invocation. This can be specified via `-Dprotobuf.skip` on the command line.
Also added unit test case and integration test case.
Closes GH-184.
> GH-184: Add parameter to skip plugin invocation.

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
- protobuf-maven-plugin/src/site/markdown/index.md
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojoTestTemplate.java
This reduces naming conflicts and ensures all parameters start with the 'protobuf.' prefix when provided via JVM system properties.
> Rename protoc.version to protobuf.compiler.version

- protobuf-maven-plugin/src/site/markdown/index.md
Update the option for generating python stubs in the language sources configuration table.
Previously, the table included `pyiEnabled` but the plugin actually needs `pythonStubsEnabled`.
Fixes #199
> Update the option for generating python stubs in the documentation

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java
Fix a bug where source counts were logged incorrectly
> Fix incorrect log message for source counts

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Missing directory roots will no longer be passed to protoc. Instead, they'll be emitted as a warning prior to the plugin source code generator being run.
If no sources are provided anywhere, the plugin will then error prior to calling protoc.
> Warn ahead of time if directories are missing and omit them from compilation

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/embed-main-sources/invoker.properties
- protobuf-maven-plugin/src/it/embed-main-sources/pom.xml
- protobuf-maven-plugin/src/it/embed-main-sources/src/main/protobuf/helloworld.proto
- protobuf-maven-plugin/src/it/embed-main-sources/src/main/protobuf/org/example/channel.proto
- protobuf-maven-plugin/src/it/embed-main-sources/src/main/protobuf/org/example/message.proto
- protobuf-maven-plugin/src/it/embed-main-sources/src/main/protobuf/org/example/user.proto
- protobuf-maven-plugin/src/it/embed-main-sources/src/test/java/org/example/helloworld/ProtobufTest.java
- protobuf-maven-plugin/src/it/embed-main-sources/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceRootRegistrar.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
Enable embedding protobuf sources that got compiled within the output classes directory for the project. This enables embedding them in any generated JAR.
Closes GH-207.
> GH-207: Implement ability to embed proto sources in output JAR

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ArgLineBuilder.java
This provides little additional beneficial detail, so is being removed. This reduces logging noise.
> Remove protoc --version call on each run

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
Changes how stdout and stderr are piped from protoc subprocesses so that their outputs get written directly to the Maven logs so that they can be directly queried should logs be redirected to a different location to stdout/stderr.
Outputs to stdout are written to info logs, and outputs to stderr are written to warn logs.
We do this via two daemon threads that consume the input streams via buffered readers.
> Write outputs of protoc invocations to the Maven logs

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/UrlResourceFetcher.java
This PR changes the way we compute the User-Agent header that we pass to URLConnection objects so that it is calculated once on initialization rather than on every single invocation.
This tidies up the logic slightly and is a little bit more efficient long-term.
> Calculate the User-Agent for URL connections on startup

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
Changes Termux detection internally to cover Android as a whole, and uses a less error prone way of detecting that environment.
> Improve Android detection

- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/site/site.xml
The unit test report is missing from the generated Maven site, which means the coverage is being reported incorrectly.
> Fix missing unit test report set on generated site

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutor.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresException.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fixtures/RandomFixtures.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutorTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresExceptionTest.java
- Refactors the threaded executor logic into a separate class
- Covers the logic with unit tests
- Implements condition that will prefer the use of Loom virtual thread pools if available on the target JVM.
> Refactor executor out into separate class that is individually testable

- .github/workflows/deploy.yml
Given Nexus has been flaky recently and I've had to manually intervene to remove tags and revert commits on multiple occasions, I'm adding in an auto-rollback step to deployments going forwards.
> Update deploy.yml to auto-rollback if deployment fails

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-277-plugin-ordering/invoker.properties
- protobuf-maven-plugin/src/it/gh-277-plugin-ordering/pom.xml
- protobuf-maven-plugin/src/it/gh-277-plugin-ordering/src/main/java/org/example/helloworld/ReactorGreetingServiceImpl.java
- protobuf-maven-plugin/src/it/gh-277-plugin-ordering/src/main/protobuf/helloworld.proto
- protobuf-maven-plugin/src/it/gh-277-plugin-ordering/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/ProtocPlugin.java
- protobuf-maven-plugin/src/site/markdown/index.md
- Add new feature that allows users to explicitly order plugins across multiple POMs by specifying `<order>12345</order>`.
- Document new behaviour.
- Document plugin common attributes in one place.
- Implement integration test for ordering.
Fixes GH-277.
> GH-277: Support explicit plugin ordering

- protobuf-maven-plugin/src/it/embed-main-sources/selector.groovy
- protobuf-maven-plugin/src/it/gh-132-duplicate-maven-dependencies/selector.groovy
- protobuf-maven-plugin/src/it/gh-134-multiple-artifact-versions/selector.groovy
- protobuf-maven-plugin/src/it/gh-135-compile-dependencies/selector.groovy
- protobuf-maven-plugin/src/it/gh-164-direct-dependency-resolution-depth-for-source-dependencies/selector.groovy
- protobuf-maven-plugin/src/it/gh-164-transitive-dependency-conflicts/selector.groovy
- protobuf-maven-plugin/src/it/gh-164-transitive-dependency-resolution-depth-for-source-dependencies/selector.groovy
- protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/selector.groovy
- protobuf-maven-plugin/src/it/gh-250-excludes/selector.groovy
- protobuf-maven-plugin/src/it/gh-250-includes/selector.groovy
- protobuf-maven-plugin/src/it/gh-267-resolve-test-jar-type/selector.groovy
- protobuf-maven-plugin/src/it/gh-267-resolve-tests-classifier/selector.groovy
- protobuf-maven-plugin/src/it/gh-277-plugin-ordering/selector.groovy
- protobuf-maven-plugin/src/it/grpc-plugin/selector.groovy
- protobuf-maven-plugin/src/it/help-goal/selector.groovy
- protobuf-maven-plugin/src/it/http-url-grpc-plugin/selector.groovy
- protobuf-maven-plugin/src/it/http-url-protoc/selector.groovy
- protobuf-maven-plugin/src/it/java-main-empty/selector.groovy
- protobuf-maven-plugin/src/it/java-main-lite/selector.groovy
- protobuf-maven-plugin/src/it/java-main/selector.groovy
- protobuf-maven-plugin/src/it/java-paths/selector.groovy
- protobuf-maven-plugin/src/it/java-test-lite/selector.groovy
- protobuf-maven-plugin/src/it/java-test/selector.groovy
- protobuf-maven-plugin/src/it/kotlin-main/selector.groovy
- protobuf-maven-plugin/src/it/kotlin-test/selector.groovy
- protobuf-maven-plugin/src/it/maven-dependency-protopath/selector.groovy
- protobuf-maven-plugin/src/it/reactor-grpc-binary-plugin/selector.groovy
- protobuf-maven-plugin/src/it/reactor-grpc-jvm-plugin/selector.groovy
- protobuf-maven-plugin/src/it/scalapb-plugin/selector.groovy
Detect if tests are running on Android and skip them as appropriate.
> Skip ITs on Android if they cannot invoke the binaries correctly

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- protobuf-maven-plugin/src/it/path-protoc/pom.xml
- protobuf-maven-plugin/src/it/path-protoc/src/test/java/org/example/helloworld/ProtobufTest.java
- scripts/bump-versions.sh
- scripts/close-nexus-repos.sh
- scripts/install-protoc-to-github-runner.sh
- scripts/site-local.sh
Use a consistent version of protoc when running path tests in CI which can also cover MacOS and Windows runners.
Bump path protoc test version of protobuf-java to v4.27.2 from v3.25.x
> Reenable protobuf path tests in CI for MacOS and Windows

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
Use the batch (DOS script) format for the execution argline when using Windows to invoke builds.
> Use batch dialect when logging invoked commands on Windows

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/Shlex.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ShlexTest.java
This appears to be unnecessary and results in noisy command line strings when running on Windows.
> Do not treat backslashes in batch scripts as special characters

- protobuf-maven-plugin/src/it/gh-299-ehcache-jaxb-resolution-failure/invoker.properties
- protobuf-maven-plugin/src/it/gh-299-ehcache-jaxb-resolution-failure/pom.xml
- protobuf-maven-plugin/src/it/gh-299-ehcache-jaxb-resolution-failure/selector.groovy
- protobuf-maven-plugin/src/it/gh-299-ehcache-jaxb-resolution-failure/src/main/protobuf/org/example/helloworld.proto
- protobuf-maven-plugin/src/it/gh-299-ehcache-jaxb-resolution-failure/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Do not fail if we have a partial dependency resolution failure
If we only have a partial dependency resolution failure, log the error
details and continue with the dependencies that we do have access to.
This prevents us having immediate issues with erroneous transitive
dependencies that we do not care about, letting Maven fail later
if the resources were actually required.
This change makes builds more resillient to poorly configured
dependencies, such as the JAXB dependency used in ehcache.
Fixes GH-299.
> GH-299: Do not fail if we have partial dependency resolution failures

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/Language.java
Remove backing ArrayList and use EnumSet directly, as it is mutable.
> Simplify EnumSet usage in Language.java

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- Improve grammar of the log outputs
- Fix an overly confusing method name.
> Improve log output in AbstractGenerateMojo.java

- protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/invoker.properties
- protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/pom.xml
- protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/selector.groovy
- protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/src/main/protobuf/org/example/helloworld.proto
- protobuf-maven-plugin/src/it/gh-327-non-zip-archive-handling/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
- Fix case sensitivity handling to match the behaviour at https://github.com/openjdk/jdk/blob/cafb3dc49157daf12c1a0e5d78acca8188c56918/src/jdk.zipfs/share/classes/jdk/nio/zipfs/ZipFileSystemProvider.java#L128
- Do not support WAR or EAR artifacts that cannot be parsed by the ZipFileSystemProvider in Java.
- Add an integration test to reproduce GH-327.
> GH-327: Cleanup tasks 

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
issue - duplicate "/src/main/protobuf" in argline
fix - there was a redundant setting of `importPaths` that overwrote the previous logic which filtered duplicates.
Fixes GH-334.
> GH-334: remove duplicate "--proto_path" logs

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
Resolve java executable using absolute path as per the `java.home` system property instead of relying on java being present on the system PATH.
Closes GH-312.
> feat: improved jvm plugin subprocess handling

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
GH-350 deprecates the use of `@Component` in Mojo classes.
The documentation suggests to use `@Parameter` or Javax CDI annotations instead to achieve dependency injection.
This PR replaces those annotations with `javax.inject.Inject` to allow GH-350 to build and closes GH-351.
> GH-351: Replace Component annotations with javax.inject.Inject.

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutor.java
- Use immutable collections in ConcurrentExecutor.
- Improve debug logging.
> Enforce immutability in ConcurrentExecutor.java

- protobuf-maven-plugin/src/it/gh-358-unpackaged-jar-plugin/invoker.properties
- protobuf-maven-plugin/src/it/gh-358-unpackaged-jar-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-358-unpackaged-jar-plugin/protoc-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-358-unpackaged-jar-plugin/protoc-plugin/src/main/java/org/example/protocplugin/ProtocPlugin.java
- protobuf-maven-plugin/src/it/gh-358-unpackaged-jar-plugin/selector.groovy
- protobuf-maven-plugin/src/it/gh-358-unpackaged-jar-plugin/some-project/pom.xml
- protobuf-maven-plugin/src/it/gh-358-unpackaged-jar-plugin/some-project/src/main/protobuf/org/example/helloworld.proto
- protobuf-maven-plugin/src/it/gh-358-unpackaged-jar-plugin/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/MavenProtocPlugin.java
- protobuf-maven-plugin/src/site/markdown/usage.md
The current solution to providing JVM plugins does not support the use of non-JAR projects. This poses a problem because we currently pass the JAR to the `java` executable via the `-jar` flag, and this will not work for class directory trees.
The main case where this is problematic is when "dogfooding" a new JVM plugin within the same Maven project and binding the test artifact to consume the plugin during the `compile` phase, which occurs before a JAR has been packaged by Maven.
Ideally, users should be using something like `maven-invoker-plugin` for this kind of testing to enable keeping the runtime environment as close to the real runtime environment as possible, but this fix is applied as a workaround for places where this is not possible or desired.
In the case that users use this …
> GH-358: Support the use of unpackaged JVM plugins

- pom.xml
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/invoker.properties
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/protoc-plugin-backend/pom.xml
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/protoc-plugin-backend/src/main/java/module-info.java
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/protoc-plugin-backend/src/main/java/org/example/protocplugin/backend/ProtocPluginBackend.java
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/protoc-plugin-frontend/pom.xml
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/protoc-plugin-frontend/src/main/java/org/example/protocplugin/frontend/Main.java
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/protoc-plugin-frontend/src/main/module-info.java
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/selector.groovy
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/some-project/pom.xml
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/some-project/src/main/protobuf/org/example/helloworld.proto
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
This PR implements changes to detect JPMS (Jigsaw) modules on the classpath for a given JVM plugin and dependencies.
All modules that are detected will be passed on the module path as well as the class path.
Fixes GH-359.
> GH-359: Pass module path to JVM plugins correctly

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
This PR introduces a couple of new flags in the JVM plugin scripts that enables tiered compilation that only runs at level 1 (client)
rather than level 2 (server) mode for JIT.
The idea here is to reduce the startup times for short-lived processes invoking JVM plugins internally.
Closes GH-392.
> GH-392: Use tiered level-1 compilation when running JVM subprocesses

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/MavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
This allows swapping implementations out in the future, and keeps concerns separated more clearly.
> Internalize dependencies on aether

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-commandline-args/invoker.properties
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-commandline-args/pom.xml
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-commandline-args/protoc-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-commandline-args/protoc-plugin/src/main/java/org/example/protocplugin/ProtocPlugin.java
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-commandline-args/some-project/pom.xml
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-commandline-args/some-project/src/main/protobuf/org/example/helloworld.proto
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-commandline-args/test.groovy
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-jvm-args/invoker.properties
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-jvm-args/pom.xml
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-jvm-args/protoc-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-jvm-args/protoc-plugin/src/main/java/org/example/protocplugin/ProtocPlugin.java
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-jvm-args/some-project/pom.xml
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-jvm-args/some-project/src/main/protobuf/org/example/helloworld.proto
- protobuf-maven-plugin/src/it/gh-397-jvm-plugin-jvm-args/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/MavenProtocPlugin.java
Adds two new attributes to the `jvmMavenPlugin` option:
- `jvmArgs` - a list of command line arguments
- `jvmConfigArgs` - a list of JVM arguments (such as `-Xmx300m` or `-Dfoo.bar=baz`).
Closes GH-397.
> GH-397: implement ability to specify JVM arguments to plugins

- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fixtures/UsesSystemProperties.java
- Demote logging to debug level
- Rename inner extension class to be clearer
- Remove self-referential import
- Mark extension as final
- Update JavaDocs
- Unmark field as volatile as it is not synchronized anyway
- Mark annotation as "Inherited"
> Tweak UsesSystemProperties.java

- protobuf-maven-plugin/src/it/gh-134-multiple-artifact-versions/test.groovy
- protobuf-maven-plugin/src/it/gh-135-compile-dependencies/test.groovy
- protobuf-maven-plugin/src/it/gh-302-runtime-scope-direct-resolution/test.groovy
- protobuf-maven-plugin/src/it/gh-302-runtime-scope-transitive-resolution/test.groovy
- protobuf-maven-plugin/src/it/gh-359-modular-jar-plugin/test.groovy
- protobuf-maven-plugin/src/it/test-dependency-resolution/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/TemporarySpace.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/generation/TemporarySpaceTest.java
- Temporary spaces are now scoped to the current goal and execution ID.
- JVM plugin hashes now include an increasing index to prevent duplicate plugins in the same execution overwriting the same files in the scratch space.
Fixes GH-421.
> GH-421: Ensure temporary spaces and plugin scratches cannot collide

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresException.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresExceptionTest.java
This will produce clearer stacktraces.
> Retain stacktrace for MultipleFailuresException

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresException.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresExceptionTest.java
This further improves error reporting to provide more details out of the box when users report issues.
> Improve MultipleFailureException message to include first cause

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceRootRegistrar.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoArchiveExtractor.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/FileUtils.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/FileUtilsTest.java
Moves all the logic that is duplicated between classes for copying a relative file tree from one file system root to another to a common helper.
> Extract out common logic for file tree rebasing

- protobuf-maven-plugin/src/it/gh-277-plugin-ordering/invoker.properties
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
- Reduce the argline log entry to be a debug log rather than info.
- Log a simple 'invoking protoc' message as info instead.
> Reduce log noise for large numbers of protoc sources

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
Currently we use absolute paths to generate unique names for archives to avoid name collision, but since we now support resolution of archives internally and recursively as part of optimisations for GH-438, there is now a potential edge case where an archive within an archive can collide with a different file tree by reusing the same name in a legal context.
Switching to using URIs to generate the digests reduces this risk, as URIs encapsulate the full source of the file tree recursively.
> GH-438: Change unique name digest generation for archives to use full URIs

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceRootRegistrar.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/SourceGlobFilter.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/SourceListing.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/SourceResolver.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Tidy up prior to the crux of GH-438's implementation to avoid confusion and ambiguity.
- Rename components relating to proto files to be clear they are operating on source files.
- Rename the SourceCodeGenerator "monolith" to ProtobufBuildOrchestrator, which more accurately describes what this component really does.
> GH-438: Rename components to be clearer for their intention

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutor.java
Correctly mark the concurrent executor as a singleton to avoid excessive thread allocation. Without this, an instance can be allocated per component that depends on this object.
> Correctly mark the concurrent executor as a singleton

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutor.java
Cached thread pools will use as many threads as needed and are suitable for short lived IO-bound operations that are performed in bulk.
> Update ConcurrentExecutor.java to use cached thread pool

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-438-incremental-compilation-no-changes/invoker.properties
- protobuf-maven-plugin/src/it/gh-438-incremental-compilation-no-changes/pom.xml
- protobuf-maven-plugin/src/it/gh-438-incremental-compilation-no-changes/src/main/protobuf/org/example/avatar.proto
- protobuf-maven-plugin/src/it/gh-438-incremental-compilation-no-changes/src/main/protobuf/org/example/channel.proto
- protobuf-maven-plugin/src/it/gh-438-incremental-compilation-no-changes/src/main/protobuf/org/example/message.proto
- protobuf-maven-plugin/src/it/gh-438-incremental-compilation-no-changes/src/main/protobuf/org/example/user.proto
- protobuf-maven-plugin/src/it/gh-438-incremental-compilation-no-changes/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/package-info.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ArgLineBuilder.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProjectInputListing.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProjectInputResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/SourceListing.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/SerializedIncrementalCache.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/SerializedIncrementalCacheModule.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/package-info.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/Digests.java
- protobuf-maven-plugin/src/site/markdown/usage.md
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/DigestsTest.java
This PR contains a number of internal changes to the way builds work to enable supporting incremental compilation on large code bases.
The crux of the change is that, upon enabling incremental compilation, the plugin will now attempt to create digests of all imports and source files. This is then compared to digests from a previous build, using the following logic:
1. If no previous digests are found, assume this is a clean build and re-generate all sources.
2. If any imports are added, removed, or updated, then perform a clean build and re-generate all sources. This is done to catch compilation errors in the sources due to changes in dependencies.
3. If any sources are deleted, then re-generate all sources. This is done to catch compilation errors in the sources due to changes in …
> GH-438: Implement incremental compilation

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java
A small optimisation for projects that both have a large number of sources and a large number of dependencies.
Rather than computing all dependency hashes and then all source hashes separately, both are now computed at the same time.
> Compute source and dependency hashes in parallel for incremental compilation

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-481-command-length/invoker.properties
- protobuf-maven-plugin/src/it/gh-481-command-length/pom.xml
- protobuf-maven-plugin/src/it/gh-481-command-length/prebuild.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocArgumentFileBuilderBuilder.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ArgumentFileBuilder.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/TeeWriter.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ArgumentFileBuilderTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/TeeWriterTest.java
This change implements the argument file mechanism for protoc
command line flags, like we do already for Java invocations. This
helps avoid build failures on Windows when a large number of files
are being generated, since Windows has somewhat esoteric limits
on the command line length. Offloading this to a file works around
this constraint.
A reproduction of the issue for Windows is also included in the test
pack, which generates a large number of random protobuf sources on
each build and feeds them into the Maven plugin.
<small>A fix for Mockito has also been included in this change to squelch
warnings about agent attachments that I was encountering on Java 21
builds.</small>
Fixes GH-481.
> GH-481: Fix bug where large builds crash on Windows 

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/SourceGlobFilter.java
Only perform inclusion checks if exclusion checks did not match each file.
This will potentially halve the number of glob lookups being performed in large codebases when exclusions are active.
> Short-circuit glob checks for SourceGlobFilter.java

- README.md
- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java
- protobuf-maven-plugin/src/site/markdown/faster-builds.md
- protobuf-maven-plugin/src/site/markdown/known-issues.md
This changes incremental compilation to be more aggressive by forcing a full rebuild if any source files change. This will work around
some of the potential edge cases that currently exist, and allow enabling this feature by default.
> Enable incremental compilation by default

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java
Remove check for deleted files since the full rebuild check in 2.8.0 will already cover this eventuality, making the additional work redundant.
> Optimise IncrementalCacheManager.java

- .github/workflows/build.yml
- protobuf-maven-plugin/src/it/protoc-descriptor-file/pom.xml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Fix regression for path parsing in Maven 3.8.2.
> Fix regression for Maven 3.8.2 in v2.9.0

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
- Rewrite Termux warning to be clearer.
- Convert "LATEST" exception into a warning to be more permissive.
> Improve ProtocResolver.java warnings

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/protoc-descriptor-file-options/invoker.properties
- protobuf-maven-plugin/src/it/protoc-descriptor-file-options/pom.xml
- protobuf-maven-plugin/src/it/protoc-descriptor-file-options/src/main/protobuf/helloworld.proto
- protobuf-maven-plugin/src/it/protoc-descriptor-file-options/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocArgumentFileBuilderBuilder.java
- protobuf-maven-plugin/src/site/markdown/basic-usage.md
- protobuf-maven-plugin/src/site/markdown/descriptor-files.md
- protobuf-maven-plugin/src/site/markdown/known-issues.md
- protobuf-maven-plugin/src/site/site.xml
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Extends GH-506 with support for descriptor configuration parameters that can be passed to protoc.
- Add three new options:
- outputDescriptorIncludeImports - pass the --include_imports flag to protoc.
- outputDescriptorIncludeSourceInfo - pass the --include_source_info flag to protoc.
- outputDescriprorRetainOptions - pass the --retain_options flag to protoc.
- Moved the documentation for descriptor files to a separate location.
- Fixed an edge case where incremental compilation could cause inconsistent descriptor file outputs. Enabling descriptor files will now disable incremental compilation.
> Add support for proto descriptor options

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapper.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/FallbackEclipseArtifactType.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapperTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/FallbackEclipseArtifactTypeTest.java
Reorganises some code around artifact mapping and implements the first set of unit tests.
> Implement initial eclipse artifact mapper tests

- .github/workflows/build.yml
- protobuf-maven-plugin/pom.xml
Following the suggestion from GH-523 to relax the Maven version constraints from `3.8.2` to `3.8`
> GH-523: Relax prerequisite constraint to Maven 3.8 from 3.8.2

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
Termux detection now uses the java.vendor property rather than a call to uname via a subprocess. This will still catch most cases so that a warning can
be emitted without needing to have complicated
subprocess handling for this single edge case. This also removes the warning for Android outside this
specific case as we do not test integration for this scenario to know whether it is an issue or not.
> Improve Termux detection semantics

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
Improves the wording and formatting of some of the more common log entries in the plugin.
Fixes some inconsistencies around use of past/present/future tense.
Logs the name of the stdout/stderr streams when reporting the outputs of protoc, along with the PID of the process.
> Improve quality of general logs

- .github/workflows/build.yml
- codecov.yml
Applies the new functionality in https://github.com/codecov/codecov-action/issues/1436 to be able to defer reporting coverage until the entire pipeline has uploaded coverage reports. This reduces noise in pull request logs.
> Defer coverage reports to the end of the CI pipeline

- README.md
- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/avatars/pom.xml
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/avatars/src/main/protobuf/avatars/avatar.proto
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/channels/pom.xml
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/channels/src/main/protobuf/channels/channel.proto
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/invoker.properties
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/metadata/pom.xml
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/metadata/src/main/protobuf/metadata/metadata.proto
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/pom.xml
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/test.groovy
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/users/pom.xml
- protobuf-maven-plugin/src/it/gh-575-configuration-import-dependencies-exclusions/users/src/main/protobuf/users/user.proto
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/MavenArtifact.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/MavenExclusion.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapper.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/site/markdown/dependencies.md
- protobuf-maven-plugin/src/site/site.xml
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapperTest.java
Add the ability to provide `<excludes>` blocks within `<sourceDependencies>` and `<importDependencies>` provided within the plugin `<configuration>` block, as requested by @jaredstehler.
Closes GH-575.
Relates to GH-555.
> GH-575: Allow excluding dependencies provided within plugin configuration

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ProtobufMavenPluginRepositorySession.java
This will enable further debugging of GH-579 to determine why repository resolution is not working as expected.
> GH-579: Temporarily disable aether artifact cache

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ProtobufMavenPluginRepositorySession.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolverTest.java
This replaces the use of a ProjectBuildingRequest to determine the project remote repositories with inspection of the current MavenProject instead.
It has been observed that ProjectBuildingRequest ignores any repositories defined in the project POM, and only considers the contenrs of the settings.xml in the user's ~/.m2.
Conversely, it was observed that the list within the current MavenProject provides the correct expected list when the user has overridden repositories in their POM.
This means that dependencies should now resolve correctly in private repositories if the user overrides them per project.
Fixes GH-579
> GH-579: Resolve dependencies from MavenProject repository list

- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/invoker-debug.properties
- protobuf-maven-plugin/src/it/invoker.properties
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/StringUtils.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/StringUtilsTest.java
Extend the functionality to not fail on dependency resolution errors to the artifact resolution mechanism within the dependency resolver backend.
Overhauled the underlying logic to avoid other edge cases due to the way Aether works being overly confusing.
> GH-582: Allow suppressing internal Artifact resolution errors for dependencies

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/PlatformClassifierFactory.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/UrlResourceFetcher.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/ProjectPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProjectInputResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/SourcePathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutor.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/SystemPathBinaryResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/TemporarySpace.java
- Fix the default prototyping behaviour of CDI dependencies that results in a number of copies of the same components being initialised on each plugin execution. Replace this with MOJO execution-scoped components instead.
- This should reduce overhead of invoking the plugin during builds.
- Replace global `@Singleton` CDI components with session-scoped components instead.
- Describe all Sisu components.
- Fix naming of SourcePathResolver to be clearer (see GH-567).
Fixes GH-586.
Closes GH-567 as no longer needed.
> GH-586: Scope CDI components to the current executon

- pom.xml
- protobuf-maven-plugin/src/site/site.xml
- Roll back maven-site-plugin to v3
Seems the newest Fluido skin is incompatible with the 4.0.0-M16
release of maven-site-plugin, and the newest 3.x version is a few
months newer. Let's wait until v4 is stable before upgrading it.
- Upgrade fluido skin to stable release
Move the fluido skin to a stable release, and track it
in the pom.xml so dependabot can start to manage it
automatically in the future.
> Update site skin version

- README.md
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutor.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutorTest.java
Large projects will currently attempt to extract a large number of JARs in memory without an explicit concurrency limit. This may result in resource exhaustion for CPU and/or memory, affecting the stability of the plugin.
This reworks the ConcurrentExecutor to use a set of sensible values that scales based on the available compute.
> GH-596: Restrict executor currency to avoid resource exhaustion

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
If we know there is nothing to compile, don't even bother performing dependency resolution. This speeds up builds that have nothing to do in them.
Closes GH-600.
> GH-600: Fail early if we know there is no work to perform

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapper.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherDependencyManagement.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojo.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapperTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fixtures/DependencyFixtures.java
This adjusts how we discover dependencies to enable Maven to resolve the project ones to paths for us
prior to actually calling the plugin. This avoids
having to use Aether directly for large numbers of dependencies on each run.
May provide performance improvements to GH-596 and GH-600.
Fixes GH-603.
> GH-603: Resolve project dependencies via Maven

- pom.xml
- protobuf-maven-plugin/src/site/markdown/additional-language-support.md
- protobuf-maven-plugin/src/site/markdown/basic-usage.md
- protobuf-maven-plugin/src/site/markdown/changing-protoc-versions.md
- protobuf-maven-plugin/src/site/markdown/dependencies.md
- protobuf-maven-plugin/src/site/markdown/descriptor-files.md
- protobuf-maven-plugin/src/site/markdown/faster-builds.md
- protobuf-maven-plugin/src/site/markdown/index.md
- protobuf-maven-plugin/src/site/markdown/known-issues.md
- protobuf-maven-plugin/src/site/markdown/requirements.md
- protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
- protobuf-maven-plugin/src/site/resources/js/configure.js
- protobuf-maven-plugin/src/site/resources/js/fluido-toc-generator.js
- protobuf-maven-plugin/src/site/site.xml
This implements a JS hook that runs once the page has loaded and generates a table of contents by sniffing out
`<h1>...<h6>` tags to construct a virtual header tree.
This allows us to make a table of contents without extending fluido or hardcoding it in Markdown for the time being, which
should improve user experience with documentation.
> Generate table of contents in markdown documentation

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/NoCacheResolutionErrorPolicy.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ProtobufMavenPluginRepositorySession.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/NoCacheResolutionErrorPolicyTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ProtobufMavenPluginRepositorySessionTest.java
While Maven itself defaults to doing this, we do not want to be caching resolution failures by default for things like the resolution of protoc. This avoids some confusing behaviour for users when developing locally.
> Disable caching of resolution errors

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationResult.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
This replaces the generic success/failure message in logs at the end of builds with a more detailed description of what the outcome actually was, which should help the user work out what to do next.
> Provide clearer final messages in logs

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojo.java
Addresses a regression introduced in GH-604 as part of the workaround for GH-603 that prevented TEST-scoped dependencies in the project being included for resolution if the user ran the 'generate' goal with custom scopes in the configuration rather than the 'generate-test' goal.
> GH-603: Fix scope detection for 'generate' goal

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/ProjectPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/ProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocArgumentFileBuilderBuilder.java
- protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
Improve codegen ordering
This breaking change alters how we determine the order to run plugin
code generation in to be able to be relative to the builtin code
generators in protoc and the descriptor file generation in protoc.
Plugins now have an order of 0 rather than 100,000 by default. The
implication of setting a negative order is that it will run prior
to builtin and descriptor generation, and a positive order will run
afterwards.
The order of language generation is also now stable between builds.
> v3.0.0 - improve how ordering of plugins works

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
Closes GH-621.
Originally this was going to be a bugfix to handle the working directory correctly when calling `mvn -f` but this appears to be totally dead code anyway, so I am just removing it.
> GH-621: Remove dead code for working directory discovery

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
- Scope per Mojo execution rather than per session for consistency with the rest of the project.
- Use functional programming style for project property and env parsing.
- Rescope test constructor.
> Refactor HostSystem to improve maintainability

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/UriResourceFetcher.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/PathConverter.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/ProtobufMavenPluginConfigurator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/UriConverter.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/package-info.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/UriProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
- protobuf-maven-plugin/src/site/markdown/changing-protoc-versions.md
- protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/UriResourceFetcherTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/PathConverterTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/plexus/UriConverterTest.java
This will allow us to later register custom protocol handlers for URLs correctly. We cannot do this at the moment because Plexus defaults to trying to parse URLs using the URL default constructor, and that only checks the system classloader for handlers that are registered via the URLStreamHandlerProvider SPI. Our issue is that whilst this would be fine in a normal application, Maven plugins utilise ClassWorlds to separate classloading for each plugin. This means we never run on the default classloader and anything we register with our ServiceLoader will be ignored.
By defining this scaffolding, we can defer parsing URLs until we enter the UrlResourceFetcher (now named UriResourceFetcher), and we can inject our own logic and lookups procedurally.
This scaffold also allows us to pass Path …
> Use a custom Plexus converter to defer URL parsing to the last minute

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Missed this in v3.1.3 by the looks of it.
> Use Path instead of File for outputDescriptorFile parameter

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/scalapb-plugin/pom.xml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcher.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/ZipUrlStreamHandlerProvider.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/resources/META-INF/services/java.net.spi.URLStreamHandlerProvider
- protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fs/ZipUrlStreamHandlerProviderTest.java
This correctly allows users to reference plugins from ZIP archives using `zip:file:path/to/archive.zip!/file.exe` rather than having to use JAR, which is unintuitive.
>     Hook up a ZIP protocol handler for URLs

- protobuf-maven-plugin/src/it/gh-277-plugin-ordering/pom.xml
- protobuf-maven-plugin/src/it/grpc-plugin/pom.xml
- protobuf-maven-plugin/src/it/http-url-grpc-plugin/pom.xml
- protobuf-maven-plugin/src/it/reactor-grpc-binary-plugin/pom.xml
- protobuf-maven-plugin/src/it/setup/pom.xml
- protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
Changes the configuration for various integration tests, as well as any documentation examples, to remove the grpc transitive dependency on javax.annotation-api.
> Omit javax.annotation-api in examples and documentation

- protobuf-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Eclipse and VSCode users can add the metadata manually with a processing instruction to the pom.xml, but this is a more convenient way to do it. The m2e plugin will pick up the lifecycle mapping metadata from the jar file in the classpath.
> MainAdd metadata for m2e lifecycle mapping

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcher.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcherTest.java
- Removed user agent injection as it does not consistently propagate to nested URL handlers such as jar:http://...
- Correctly handle FileNotFoundException for nested URLs when the file does not exist, rather than raising a ResolutionException and halting the build. This fixes optional resolution semantics.
- Disallow downloading most URLs if offline mode is enabled. Any URL resolution that does not operate on file:, jar:file:, zip:file:, or jrt: will now trigger an exception during resolution if offline mode is enabled. This fixes behaviour that was enabled for GH-668 in GH-670 that allows users to run this Maven plugin in offline mode (e.g. during NIX builds, or in airgapped systems).
- File scheme matching is now case sensitive to match other behaviours elsewhere.
- Log warnings when …
> Improve URL resolution semantics and behaviours

- protobuf-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Sorry, I didn't read the docs correctly (https://eclipse.dev/m2e/documentation/m2e-making-maven-plugins-compat.html). This change should fix it so the plugin actually runs when we need it.
> Wrong flag value for code generation plugin

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/grpc-plugin/test.groovy
- protobuf-maven-plugin/src/it/per-plugin-output-paths/invoker.properties
- protobuf-maven-plugin/src/it/per-plugin-output-paths/pom.xml
- protobuf-maven-plugin/src/it/per-plugin-output-paths/src/main/java/org/example/helloworld/ReactorGreetingServiceImpl.java
- protobuf-maven-plugin/src/it/per-plugin-output-paths/src/main/protobuf/helloworld.proto
- protobuf-maven-plugin/src/it/per-plugin-output-paths/src/test/java/org/example/helloworld/ReactorGreetingServiceImplTest.java
- protobuf-maven-plugin/src/it/per-plugin-output-paths/test.groovy
- protobuf-maven-plugin/src/it/reactor-grpc-jvm-plugin/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/ProjectPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/ProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/ResolvedProtocPlugin.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocExecutor.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/targets/PluginProtocTarget.java
- protobuf-maven-plugin/src/site/markdown/using-protoc-plugins.md
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/plugins/ProjectPluginResolverTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/plugins/ProtocPluginTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/protoc/targets/PluginProtocTargetTest.java
Users can now target specific paths for specific plugins in the same execution by overriding the overall output directory with one that is set per plugin.
Remaining work:
- Integration tests
> Implement support for custom per-plugin output paths

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/java-main-legacy-source-directory/invoker.properties
- protobuf-maven-plugin/src/it/java-main-legacy-source-directory/pom.xml
- protobuf-maven-plugin/src/it/java-main-legacy-source-directory/src/main/proto/helloworld.proto
- protobuf-maven-plugin/src/it/java-main-legacy-source-directory/src/test/java/org/example/helloworld/ProtobufTest.java
- protobuf-maven-plugin/src/it/java-main-legacy-source-directory/test.groovy
- protobuf-maven-plugin/src/it/java-test-legacy-source-directory/invoker.properties
- protobuf-maven-plugin/src/it/java-test-legacy-source-directory/pom.xml
- protobuf-maven-plugin/src/it/java-test-legacy-source-directory/src/test/java/org/example/helloworld/ProtobufTest.java
- protobuf-maven-plugin/src/it/java-test-legacy-source-directory/src/test/proto/helloworld.proto
- protobuf-maven-plugin/src/it/java-test-legacy-source-directory/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojo.java
- protobuf-maven-plugin/src/site/markdown/basic-usage.md
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojoTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojoTest.java
> GH-687: Add src/main/proto and src/test/proto as directory roots for migration purposes

- .github/workflows/build.yml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/PlatformClassifierFactory.java
- protobuf-maven-plugin/src/site/markdown/requirements.md
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/PlatformClassifierFactoryTest.java
- scripts/install-protoc-to-github-runner.sh
Force Windows 11 ARM builds to use the x86_64 release of protoc and related plugins to enable interop via Prism emulation.
This enables Windows 11 ARM to use this plugin out of the box.
Fixes GH-700.
> GH-700: Windows 11 ARM plugin compatibility

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/digests/DigestPlexusConverter.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/digests/DigestPlexusConverterTest.java
Replace the existing hardcoded digest alias mapping that maps variants of strings such as 'sha256' and 'sha-256' back to the JVM supported algorithm name 'SHA-256' with a treemap comparator that compares inputs ignoring case and separators such as '-'.
This allows the list to dynamically support whatever the current JVM allows in the list of supported aliases.
> Replace hardcoded digest aliases with dynamic equivalence

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocExecutor.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocInvocation.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
I have observed that the internals of protoc have several magic environment variables dotted around that can be set to influence internal behaviours. Likewise, protoc plugins may wish to use various environment variables as overrides for internal settings.
This change adds support for overriding environment variables that are passed to protoc internally.
> Support overriding envvars passed to protoc

- pom.xml
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/gh-762-additional-args/invoker.properties
- protobuf-maven-plugin/src/it/gh-762-additional-args/pom.xml
- protobuf-maven-plugin/src/it/gh-762-additional-args/selector.groovy
- protobuf-maven-plugin/src/it/gh-762-additional-args/src/main/protobuf/helloworld.proto
- protobuf-maven-plugin/src/it/gh-762-additional-args/src/test/java/org/example/helloworld/ProtobufTest.java
- protobuf-maven-plugin/src/it/gh-762-additional-args/test.groovy
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/GenerationRequest.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocExecutor.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocInvocation.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
This enables users pinned to old versions of protoc to utilise flags such as `--experimental_allow_proto3_optional`.
Closes GH-762.
> GH-762: Allow passing additional flags to protoc

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/digests/Digest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/digests/DigestTest.java
A bug is present where bytes <10 in decimal value produce invalid digests because toHexString produces a non-zero padded hex digit pair.
This addresses that issue to compute digests correctly in that edge case.
Example:
```
- Before 41d8dfe07cfa2111d75a6b318c4e35e2f6bab9daf0d5b0748acb162bb99fa4
- After  41d8dfe07cfa2111d75a6b318c4e35e2f6bab9daf0d5b0748acb162bb909fa04
^   ^
```
> Fix a bug in digest hex representations for byte values <10

- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java
Allows the protobuf-maven-plugin to traverse `*.ear` and `*.war` files correctly, given that they are valid ZIP archives.
> Update ProtoSourceResolver.java to handle WAR and EAR dependencies

- .github/workflows/build.yml
- .gitignore
- protobuf-maven-plugin/pom.xml
- protobuf-maven-plugin/src/it/WRITING_ITS.md
- protobuf-maven-plugin/src/it/setup/pom.xml
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/MavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcher.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/BinaryPluginResolver.java
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolverTest.java
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fs/UriResourceFetcherTest.java
- scripts/install-protoc-to-github-runner.sh
- scripts/prepare-runner.sh
- Artifact resolution API now focuses on resolving executables specifically, rather than any artifact types, since we only use it for executables.
- Artifact resolution API now copies resolved executables to the temporary space and marks them as executable. This avoids changing file permissions on artifacts within the local repository, which is deemed racy and unsafe per guidance from @cstamas in https://github.com/apache/maven-resolver/issues/1577
- Removed special handling of file URIs in UriResourceFetcher, as we now want executables on the local file system to be copied rather than modifying their permissions in-place. This also fixes a potential issue where builds could fail if projects relied on a local file owned by a different user.
- UriResourceFetcher now allows setting the …
> GH-792: Avoid modifying file permissions in ~/.m2 for executables

- README.md
- protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
- protobuf-maven-plugin/src/site/markdown/other-language-support.md
- protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
Deprecate for removal any functionality we do not wish to continue to maintain.
---
* Native protoc outputs with no native tooling/toolchains, or that is otherwise difficult to test
* Objective-C - no common tooling exists in Maven.
* C++ - no common tooling exists in Maven.
* C# - Plexus tooling exists, but users are encouraged to use MSBuild or similar.
* PHP - no common tooling exists.
* Rust - no common tooling exists, users will prefer to use Cargo.
* Support for languages with JVM implementations, or GraalVM implementations, **will be kept**. This includes Java, Kotlin, Ruby (via JRuby and GraalRuby), Python (via Jython and GraalPython), and Python stubs (complimenting Python).
* Users utilising deprecated languages can move to passing the flags directly via `<arguments/>` to …
> GH-822: provisionally deprecate functionality that is unhelpful/confusing
