ascopes/protobuf-maven-plugin

pom.xml
src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java
src/main/java/io/github/ascopes/protobufmavenplugin/execute/ProtocExecutionException.java
src/main/java/io/github/ascopes/protobufmavenplugin/package-info.java
src/main/java/io/github/ascopes/protobufmavenplugin/resolve/ProtocResolutionException.java

Add nullability annotations to help with code readability.

Implement JSpecify nullability annotations.

---

src/site/markdown/index.md

Improvements to documentation.

Improve idocumentation

---

src/main/java/io/github/ascopes/protobufmavenplugin/platform/HostEnvironment.java

Remove duplicate code, and simplify.

Refactor HostEnvironment

---

src/main/java/io/github/ascopes/protobufmavenplugin/dependency/JvmPluginResolver.java
src/main/java/io/github/ascopes/protobufmavenplugin/generate/TemporarySpace.java
src/main/java/io/github/ascopes/protobufmavenplugin/source/ProtoArchiveExtractor.java
src/test/java/io/github/ascopes/protobufmavenplugin/generate/TemporarySpaceTest.java

Extract the logic for temporary path management into a separate component so that it is kept consistent.

Define temporary paths consistently

---

src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java

This removes the use of sets and uses lists for consistent ordering and build reproducability.
This also replaces the use of Strings with nio Path objects to manage validation and parsing automatically.

Simplify logic in AbstractBaseMojo

---

src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java

Fixes renderable code snippets to display correctly in JavaDocs.

Fix formatting of code snippets in JavaDocs

---

src/main/java/io/github/ascopes/protobufmavenplugin/execute/ArgLineBuilder.java
src/main/java/io/github/ascopes/protobufmavenplugin/execute/CommandLineExecutor.java
src/main/java/io/github/ascopes/protobufmavenplugin/generate/SourceCodeGenerator.java

Provide details about libprotoc upon running the plugin.

Log the protoc version info during builds

---

.github/workflows/build.yml

- Run CI on s390x, aarch64, and ppc64le platforms.
Closes GH-82.
Closes GH-83.

Run CI on aarch64, ppc64le and s390x

---

src/it/java-paths/invoker.properties
src/it/java-paths/pom.xml
src/it/java-paths/src/main/other-protobuf-dir/helloworld.proto
src/it/java-paths/src/test/java/org/example/helloworld/ProtobufTest.java
src/it/java-paths/test.groovy
src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java

Proposed solution: Use File at the declaration, but convert immediately to Path

fixes issue #129 by using File in the configuration

---

pom.xml

GH-126: Update Maven GPG plugin

---

src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java

Improves documentation of defaults.

Improve optional param documentation

---

.github/workflows/build.yml

Configure the codecov v4 action.

Use codecov v4

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/execute/ArgLineBuilder.java

This allows more customisation behaviour to be injected in later, and makes the implementation less error prone for future usage.

Restructure how the argline builder operates to defer creation.

---

protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/channel-protos/pom.xml
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/channel-protos/src/zip/channels/channel.proto
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/chat-platform-models/pom.xml
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/invoker.properties
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/message-protos/pom.xml
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/message-protos/src/zip/messages/message.proto
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/pom.xml
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/selector.groovy
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/user-protos/pom.xml
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/user-protos/src/zip/users/avatar.proto
protobuf-maven-plugin/src/it/gh-172-transitive-dependency-conflicts/user-protos/src/zip/users/user.proto

So that this is not forgotten, I am moving this reproduction onto develop and setting a flag to expect it to fail until GH-172 has a solution.

Add reproduction for GH-172 to main branch

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependency/UrlResourceFetcher.java

Simplify the URL resource fetcher to remove the custom HTTP mechanism as we really do not need it.
Prerequisite to simplifying bits of the solution in #182 via #189.

Simplify the URL resource fetcher mechanism

---

.github/workflows/build.yml

Attempting to get IBM and Arm builds working again.

Re-enable cross platform builds

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java

Tidy up null checks in AbstractGenerateMojo to use stream operations consistently where possible.

Tidy up null checks in AbstractGenerateMojo.java

---

.github/workflows/deploy.yml
pom.xml
protobuf-maven-plugin/pom.xml

GH-202: Fix broken JaCoCo reports in generated site

---

pom.xml
protobuf-maven-plugin/src/it/scalapb-plugin/invoker.properties
protobuf-maven-plugin/src/it/scalapb-plugin/pom.xml
protobuf-maven-plugin/src/it/scalapb-plugin/selector.groovy
protobuf-maven-plugin/src/it/scalapb-plugin/src/main/protobuf/helloworld.proto
protobuf-maven-plugin/src/it/scalapb-plugin/src/main/scala/org/example/helloworld/GreetingServiceImpl.scala
protobuf-maven-plugin/src/it/scalapb-plugin/src/test/scala/org/example/helloworld/GreetingServiceImplTest.scala
protobuf-maven-plugin/src/it/scalapb-plugin/test.groovy

Adds an integration test making use of Scala 3 and the ScalaPB library at https://scalapb.github.io/

Add ScalaPB plugin integration test

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoArchiveExtractor.java

Assist in build reproducibility by keeping extracted file modification timestamps consistent between builds.
Anything extracted from an archive will now use the last modification timestamp of the archive that it was extracted from.

Inherit JAR/ZIP modified timestamps during content extraction

---

protobuf-maven-plugin/pom.xml

Some reports do not render correctly, so have been removed.

Disable some reports on the site

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java

Fixes [GH-269](https://github.com/ascopes/protobuf-maven-plugin/issues/269)

Add support for custom plugin code injection

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java

Fixes [GH-271](https://github.com/ascopes/protobuf-maven-plugin/issues/271)

GH-271: Use explicit map of required path environment variable values

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojo.java
protobuf-maven-plugin/src/site/markdown/index.md

Extension of the work done by @virgilsky in GH-271. Documents the concrete behaviour that is now enforced.

GH-271: Document path resolution rules

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java

Add logging to HostSystem to allow the inclusion of this info in the future when users provide debug logs in issues.

Improve logging in HostSystem for future diagnostics

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java

- Disambiguate Aether and Maven Dependency
- Remove abuse of Optional, use procedural logic instead
- Add missing documentation
- Reformat some lines to be more readable

Tidy up AetherMavenArtifactPathResolver.java

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java

GH-304: Fix potential NPE in AetherMavenArtifactPathResolver#extensionToType

---

.github/workflows/build.yml
.github/workflows/validate.yml

Allow CI to run on branch push events to allow testing without a PR in place first.

Improve CI

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java

- Use logger for each line of the reported argline
- Remove distracting stdout/stderr prefixes on logs as we use the logger level to describe the stream.

Improve process logging

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocResolver.java

Improves warnings and exception messages produced by ProtocResolver during erroneous edge cases at runtime.

Improve error messages in ProtocResolver.java

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java

- Improve error messages and logs in AetherMavenArtifactPathResolver
- Remove duplicate code in AetherMavenArtifactPathResolver

Improve errors in AetherMavenArtifactPathResolver.java, remove duplicate code

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/SourceCodeGenerator.java

- Improve exception and log messages
- Improve the "nothing to do!" messages

Improve messages in SourceCodeGenerator.java

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoArchiveExtractor.java

This provides clearer error messages to diagnose GH-372.

GH-327: Report offending paths when failing to open ZIP archives

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java

Adds tests for GH-312's solution.

GH-312: Move solution into HostSystem class and add unit tests

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProtoSourceResolver.java

- Add detection of XML/POM files in ProtoSourceResolver, as we know those are invalid configurations on the user's behalf.
- Promote the debug log about other unknown dependency types to a warning, as it means something else is misconfigured that may not be intentional.

Explicitly handle invalid POM dependencies in ProtoSourceResolver

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java

Fix handling of Windows path separators in classpaths.

GH-358: Fix handling of Windows path separators in classpaths

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Integrates an action to ensure build logs appear on GitHub as artifacts as needed.

Upload build logs to GitHub

---

protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/PlatformClassifierFactoryTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/fixtures/RandomFixtures.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/mojo/AbstractGenerateMojoTestTemplate.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/plugins/MavenProtocPluginTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ConcurrentExecutorTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/DigestsTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/FileUtilsTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/MultipleFailuresExceptionTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ResolutionExceptionTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/TemporarySpaceTest.java

Perform a small tidyup of unit test classes to fix warnings and duplication noise

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java

If exceptions are raised by artifact results, then the artifact may be null, which we are not currently reporting correctly.

Handle artifact resolution failures correctly with Aether rather than raising an NPE

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/incremental/IncrementalCacheManager.java

Refactor some of the propositional logic in the incremental cache manager

Simplify propositional logic within IncrementalCacheManager.java

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/plugins/JvmPluginResolver.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/ArgumentFileBuilder.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/TeeWriter.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/ArgumentFileBuilderTest.java

This irons out some argument file parsing edge cases in protoc for GH-481

GH-481: Adhere to protoc argument file rules correctly

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherArtifactMapper.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolver.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherResolver.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/WildcardAwareDependencyTraverser.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherMavenArtifactPathResolverTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/ProtobufMavenPluginRepositorySessionTest.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/WildcardAwareDependencyTraverserTest.java

Initial tests for the aether package, and a slight restructure.

Initial Aether tests

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/generation/ProtobufBuildOrchestrator.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/ProtocArgumentFileBuilderBuilder.java

Adds null check for descriptor file

---

.github/workflows/build.yml
README.md
pom.xml

Updates the CI pipeline to include Maven 4.0 in builds.

Run CI on Maven 4

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/CommandLineExecutor.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/protoc/OutputRedirectorDaemon.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/protoc/OutputRedirectorDaemonTest.java

- Move logic to a separate class.
- Fixes a bug logging stderr on the latest version.

Improve handling of protoc output redirection

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/utils/HostSystem.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/utils/HostSystemTest.java

Any invalid paths in the system $PATH that cannot
be correctly parsed using the default platform file system will now be logged as a warning and dropped from the effective system path when discovering
system binaries, rather than raising an exception
and failing Guice/Sisu on the bean binding stage,
which would effectively crash the entire plugin.
Fixes GH-557.

GH-557: Drop invalid $PATH entries rather than crashing

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherDependencyManagement.java
protobuf-maven-plugin/src/test/java/io/github/ascopes/protobufmavenplugin/dependencies/aether/AetherDependencyManagementTest.java

- Fix handling of duplicate dependencies
- Fix handling of versioned managed dependencies

GH-555: fix dependency management for versioned and duplicate dependencies

---

.github/workflows/build.yml
protobuf-maven-plugin/src/it/setup/pom.xml

Move from Maven 4.0.0-rc-2 to 4.0.0-rc-3.

Update build.yml to use Maven 4.0.0-rc-3

---

pom.xml
protobuf-maven-plugin/pom.xml
protobuf-maven-plugin/src/it/gh-299-ehcache-jaxb-resolution-failure/pom.xml

Move a bunch of overrides from protobuf-maven-plugin to protobuf-maven-plugin-parent instead.

Move implementation details into the global pom.xml

---

protobuf-maven-plugin/src/it/protoc-descriptors/test.groovy

Add missing test to descriptors IT

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/deploy.yml
.github/workflows/security.yml
pom.xml

GH-641: Migrate builds to release to the new Maven Central registry

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/sources/ProjectInputResolver.java

Fix a regression in ProjectInputResolver that incorrectly filters import paths with the includes/excludes filters. We do not want to be doing this, because we may still wish to import sources without generating code from them.

Fix regression in ProjectInputResolver.java for file filtering of imports

---

pom.xml

This includes new pages on the Maven site that reports the project change history.

Generate changelogs for the site

---

pom.xml

This does not work correctly by default without extra tooling.
This reverts commit 9ee664888ed6668ac4268d103662a1b514c163cf.

Revert "Generate changelogs for the site (#661)"

---

protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/MainGenerateMojo.java
protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/mojo/TestGenerateMojo.java

See https://github.com/ascopes/protobuf-maven-plugin/issues/668 for background and reasoning.

Allow running in offline mode

---

protobuf-maven-plugin/src/site/markdown/examples.md
protobuf-maven-plugin/src/site/site.xml

Add examples for using protobuf-maven-plugin in various scenarios
Closes #652

Add examples for using protobuf-maven-plugin in various scenarios

---

protobuf-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml

Sorry for this. I promise this time it works and I tested it in the IDE (it's not really easy to test without hacking jar files).

Actual working m2e metadata file

---

.github/workflows/build.yml
scripts/install-protoc-to-github-runner.sh

Run CI on ARM runners as well as AMD64.

Configure ARM runners

---

.github/workflows/build.yml

Use v5 codecov action
